### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by DavidWittman** [griggheo/ansible-consul-template#19]
Would you mind tagging a release so that I can use this role in a [Galaxy requirements file](https://docs.ansible.com/ansible/galaxy.html#advanced-control-over-role-requirements-files) without having to use master?

**Comment by griggheo** [comment]
Tagged release 1.0.0 code name "avocet" (I like birds :)

https://github.com/griggheo/ansible-consul-template/releases/tag/1.0.0
