### ISSUE TITLE
New version tag.

### ISSUE THREAD

**Issue by nmische** [griggheo/ansible-consul-template#28]
Any chance you could tag the latest version as `1.1.0`?

**Comment by griggheo** [comment]
Done.

**Comment by nmische** [comment]
Awesome, thanks!

**Comment by palmerabollo** [comment]
@griggheo Is it possible to publish it to ansible galaxy as well?

**Comment by griggheo** [comment]
I created a new release 1.1.1 and also pushed it to ansible-galaxy.

**Comment by palmerabollo** [comment]
Great. Thank you for your prompt answer.
