### ISSUE TITLE
consul_template_config_dir is not defined

### ISSUE THREAD

**Issue by palmerabollo** [griggheo/ansible-consul-template#29]
Sorry to bother you again. I think there is a bug in the latest version (1.1.1) because you use the variable `consul_template_config_dir` ([see commit](https://github.com/griggheo/ansible-consul-template/commit/f719b9c964cc7d23838908b9057035e6e55aa652#diff-31350bc3e48f74ee48e3dee5d73b2398R5)) instead of `consul_template_use_config_dir`.

**Comment by griggheo** [comment]
Fixed, thanks! Issued a new release 1.1.2
