### ISSUE TITLE
Release the new version on ansible-galaxy ? 

### ISSUE THREAD

**Issue by JGodin-C2C** [griggheo/ansible-consul-template#47]
Everything is in the title :) 

Looks like the actual version is not the current one 

https://galaxy.ansible.com/griggheo/consul-template

regards

**Comment by JGodin-C2C** [comment]
A little ping here :)

J\x00

**Comment by griggheo** [comment]
Yup I'll take care of this today, thanks for the reminder :)

**Comment by griggheo** [comment]
I made a new release 1.2.3 in github and imported it in ansible-galaxy.
Please let me know if it works for you.


https://github.com/griggheo/ansible-consul-template/releases/tag/1.2.3

https://galaxy.ansible.com/griggheo/consul-template


Grig

**Comment by JGodin-C2C** [comment]
Looks good to me, thanks Grig !
J\x00
