### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by JGodin-C2C** [griggheo/ansible-consul-template#53]
Hello @griggheo ! 
Is it possible to release the latest version of your module ? 
I actually like the latest PR and was going to do it and found somebody already did it ( Thanks @wilfriedroset )

j\x00

**Comment by griggheo** [comment]
Done - released 1.2.5 on both GitHub and Ansible Galaxy. Thanks for your support @JGodin-C2C and @wilfriedroset !
