### ISSUE TITLE
The consul-template system service is run as the root user

### ISSUE THREAD

**Issue by awarner-greshamtech** [griggheo/ansible-consul-template#55]
It would be more secure to allow the option of creating a specific "consul-template" user and group and use these for file permissions and for running the system service.

**Comment by griggheo** [comment]
Do you still want to create a PR for this?

**Comment by awarner-greshamtech** [comment]
Hello, yes, we are just doing some internal testing and then I will raise a PR.

**Comment by awarner-greshamtech** [comment]
Hello - PR raised for this issue ( https://github.com/griggheo/ansible-consul-template/pull/57 ). I've also added some molecule tests which you may be able to run to verify the existing behaviour is not effected by the changes.
